#install.packages("ggplot2")
library(ggplot2)
rm(list=ls())
data(ChickWeight)
names(ChickWeight)
ggplot(ChickWeight, aes(x=Time,y=weight,colour=Diet,group=Chick))+geom_line()
ggplot(ChickWeight, aes(x=Time,y=weight,colour=Diet))+geom_point(alpha=.3)+geom_smooth(alpha=.2, size=1)
ggplot(ChickWeight, aes(x=Time,y=weight,colour=Diet))+geom_smooth(alpha=.4, size=3)
# install.packages("sqldf")
# library(sqldf)
# sqldf("select count(*) from ChickWeight where Time like '21'")
dim(ChickWeight[ChickWeight$Time==21,])
ggplot(subset(ChickWeight, Time==21), aes(x=weight, colour=Diet)) + geom_density()
ggplot(subset(ChickWeight, Time==21), aes(x=weight, fill=Diet)) + geom_histogram(colour="black", binwidth=50) + facet_grid(Diet~.)
# Point Graph
data(mtcars)
names(mtcars)
head(mtcars)
p <- qplot(wt, mpg, colour=hp, data = mtcars)
p + coord_cartesian(ylim = c(0,40))
p + scale_colour_continuous(breaks = c(100,300))
p + guides(colour = "colourbar")
m <- mtcars[1:10,]
p %+% m
c <- ggplot(mtcars, aes(factor(cyl)))
c + geom_bar()
c + geom_bar(fill = "red")
c + geom_bar(colour = "red")
c + geom_bar(fill = "white", colour = "red")
k <- ggplot(mtcars, aes(factor(cyl), fill=factor(vs)))
k + geom_bar()
names(mtcars)
mtcars
#install.packages("ggplot2movies")
library(ggplot2movies)
data(movies)
head(movies)
dim(movies)
m <- ggplot(movies, aes(x = rating))
m + geom_histogram()
m + geom_histogram(aes(fill=..count..))
names(movies)
#Line Graph
data(economics)
head(economics)
dim(economics)
names(economics)
summary(economics)
b <- ggplot(economics, aes(x = date, y = unemploy))
b + geom_line()
b + geom_point()
b + geom_point(colour="red")
df <- data.frame(x=rnorm(5000), y=rnorm(5000))
data.frame(df)
summary(df)
dim(df)
h <- ggplot(df, aes(x,y))
h + geom_point()
h + geom_point(alpha=0.5)
h + geom_point(alpha=0.1)
p <- ggplot(mtcars, aes(wt,mpg))
p + geom_point(size=4)
p + geom_point(aes(colour=cyl, size=4))
p + geom_point(aes(shape=factor(cyl), colour=factor(cyl), size=4))
library(reshape)
library(plyr)
library(ggplot2)
rescale01 <- function(x)(x - min(x))/diff(range(x))
ec_scaled <- data.frame(date = economics$date, colwise(rescale01)(economics[,-(1:2)]))
ecm <- melt(ec_scaled, id="date")
ecm
f <- ggplot(ecm,aes(date,value))
f + geom_line(aes(linetype=variable)) 
# , colour=factor(variable) #
data(diamonds)
dim(diamonds)
names(diamonds)
head(diamonds)
k <- ggplot(diamonds, aes(carat, ..density..))
k1 <- k + geom_histogram(binwidth=0.2)
k1 + facet_grid(.~cut)
w <- ggplot(diamonds, aes(clarity, fill=cut))
w + geom_bar()
df <- data.frame(x = 1:10, y = 1:10)
f <- ggplot(df, aes(x=x, y=y))
f + geom_line(linetype=2)
f + geom_line(linetype="dotdash")
??aes
# dotdash type０⊕ no.4
f + geom_line(linetype=4)
p <- ggplot(mtcars, aes(wt,mpg))
p + geom_point(size=4)
p + geom_point(aes(size=qsec))
??aes
p + geom_point(size=2.5) + geom_hline(yintercept = 25, size = 3.5)
p + geom_point()
p + geom_point(shape=5)
p + geom_point(shape="k", size=3)
p + geom_point(shape=".")
p + geom_point(shape=NA)
summary(mtcars)
#▽???⊕見 shape ∫╱???／
p + geom_point(aes(shape=factor(cyl)))
# ＿﹌＿﹌０∫ 25＿﹉╳?? shape ∫╱???／
df2 <- data.frame(x = 1:5, y = 1:25, z = 1:25)
s <- ggplot(df2, aes(x=x, y=y))
s + geom_point(aes(shape=z), size=4) + scale_shape_identity()
# diamonds data set０∫ linear modeling
data(diamonds)
names(diamonds)
head(diamonds)
dmod <- lm(price~cut, data=diamonds)
cuts <- data.frame(cut = unique(diamonds$cut), 
                   predict(dmod,data.frame(cut = unique(diamonds$cut)), se = TRUE)
                   [c("fit", "se.fit")])
se <- ggplot(cuts, aes(x=cut, y=fit, ymin = fit - se.fit, ymax = fit + se.fit, colour=cut))
se + geom_pointrange()
# ???赤╳＝ ⊕走⊕???０見 ＿℅╳± - 1 
p <- ggplot(mtcars, aes(wt, mpg)) + geom_point()
p
p + annotate("rect", xmin = 2, xmax = 3.5, ymin = 2, ymax = 25, fill = "dark grey", alpha = 0.5)
# ???赤╳＝ ⊕走⊕???０見 ＿℅╳± - 2 (graph ∮芋﹠I)
qplot(disp, wt, data = mtcars) + geom_smooth()
p <- qplot(disp, wt, data = mtcars) + geom_smooth()
p + scale_x_continuous(limits = c(325,500)) #∮芋﹠I
ggplot(diamonds, aes(carat, price)) + stat_bin2d(bin = 25, colour="grey50")
d <- ggplot(diamonds, aes(carat, price)) + stat_bin2d(bin = 25, colour="grey50")
d + scale_x_continuous(limits = c(0,2)) # ∮芋﹠I
# graph ╳＝帚℅
qplot(cut, price, data=diamonds, geom="boxplot")
qplot(cut, price, data=diamonds) + geom_boxplot() # ±∮＿＿０⊕ ＿﹞＿◤
last_plot() + coord_flip() # ４±╳??４３ ▽???３╳╳?? plot０見 目∵＿E休E∫???０４３走 ⊕赤＿E
qplot(cut, data=diamonds, geom="bar")
last_plot() + coord_flip()
h <- qplot(carat, data=diamonds, geom="histogram")
h
h + coord_flip()
h + coord_flip() + scale_x_reverse()
# ﹠??屆A∫??? ⊕赤足??４Ｄ y∵Ｆ帚﹉ ∫???目∵
time <- seq(7000, 3400, -200)
head(time)
pop <- c(200, 400, 450, 500, 300, 100, 400, 700, 830, 1200, 400, 350, 200, 700, 370, 800, 200, 100, 120)
grp <- c(2,5,8,3,2,2,4,7,9,4,4,2,2,7,5,12,5,4,4)
med <- c(1.2, 1.3, 1.2, 0.9, 2.1, 1.4, 2.9, 3.4, 2.1, 1.1, 1.2, 1.5, 1.2, 0.9, 0.5, 3.3, 2.2, 1.1, 1.2)
par(mar=c(5, 12, 4, 4) + 0.1)
plot(time, pop, axes=F, ylim=c(0,max(pop)), xlab="", ylab="", type="l", col="black", main="", xlim=c(7000,3400))
points(time, pop, pch=20, col="black")
axis(2, ylim=c(0,max(pop)), col="black", lwd=2)
mtext(2, text="Population", line=2)
par(new=T)
plot(time, med, axes=F, ylim=c(0,max(med)), xlab="", ylab="", type="l", lty=2, main="", xlim=c(7000,3400), lwd=2)
points(time, med, pch=20)
axis(2, ylim=c(0,max(med)), lwd=2, line=3.5)
mtext(2, text="Median Group Size", line=5.5)
par(new=T)
plot(time, grp, axes=F, ylim=c(0,max(grp)), xlab="", ylab="", type="l", lty=3, main="", xlim=c(7000,3400), lwd=2)
points(time, grp, pch=20)
axis(2, ylim=c(0,max(grp)), lwd=2, line=7)
mtext(2, text="Number Of Groups", line=9)
par(new=T)
axis(1, pretty(range(time), 10))
mtext("cal BP", side = 1, col = "black", line=2)
legend(x=7000, y=12, legend=c("Population", "Median Group Size", "Number of Groups"), lty = c(1,2,3))